### ISSUE TITLE
[Question]使用DNSPod作为Local DNS

### ISSUE THREAD

**Issue by shikkoku** [IrineSistiana/mos-chinadns#24]
我尝试将上游服务器中的本地服务器变更为DNSPod提供的公共DNS（刚推出公测的DoT和DoH）
https://www.v2ex.com/t/690811
但这样设置后无法正常解析国内域名了
```
# 上游服务器设定
server:
    # 本地服务器设定
    local:
        addr: "162.14.21.56:443" # 服务器地址。留空表示禁用该服务器。
        protocol: "doh" # 服务器协议。`tcp`|`udp`|`doh`|`dot`其中之一。留空默认`udp`。
        socks5: "" # socks5代理服务器地址。注意：暂不支持udp协议，不支持认证。

        # TCP设定，仅`protocol`为`tcp`时有用。
        tcp:
            idle_timeout: 10 # 空连接超时时间。单位: 秒。0表示禁用连接重用。

        # DoT设定，仅`protocol`为`dot`有用。
        dot:
            server_name: "doh.pub" # [必需] 服务器的域名/证书名。
            idle_timeout: 10 # 空连接超时时间。单位: 秒。0表示禁用连接重用。

        # DoH设定，仅`protocol`为`doh`有用。
        doh:
            url: "https://doh.pub/dns-query" # [必需] DoH的URL。

        deny_unusual_types: false # 是否屏蔽不常见(包含多个Question、非A和AAAA)请求。
        deny_results_without_ip: true  # 是否屏蔽没有IP的A和AAAA应答。
        check_cname: true # 域名策略(见下)是否也检查返回应答中的CNAME记录(CNAME深度检查)。
```

另外我尝试使用 addr: "119.29.29.29:53“ protocol: "udp"也同样解析不出来国内域名。

换成alidns后不论是DOT和DOH均正常，不使用MOS-chinadns，用119.29.29.29正常解析。
