### ISSUE TITLE
安装运行后无法查询/解析以及不能用Quad 101的doh？

### ISSUE THREAD

**Issue by leon911000** [IrineSistiana/mos-chinadns#28]
**出现了什么问题**

安装运行后不能用Quad 101的doh？

cmd命令行nslookup查询均返回“找不到 www.xxx.com（所有国外网址）: No response from server”

```
time="2020-07-30T05:52:04+08:00" level=info msg="main: mos-chinadns ver: v1.2.2-0-g5df988c"
time="2020-07-30T05:52:04+08:00" level=info msg="main: arch: amd64 os: windows"
time="2020-07-30T05:52:04+08:00" level=info msg="newIPPolicies: ip list ./chn.list loaded, length 7189"
time="2020-07-30T05:52:04+08:00" level=info msg="newDomainPolicies: domain list ./chn_domain.list loaded, length 74917"
time="2020-07-30T05:52:04+08:00" level=info msg="main: udp server started"
time="2020-07-30T05:52:04+08:00" level=info msg="main: tcp server started"
time="2020-07-30T05:52:08+08:00" level=warning msg="exchangeDNS: remote server failed after 172ms: doHTTP: http request failed: Get \"https://dns.twnic.tw/dns-query?dns=AAABAAABAAAAAAAAA2NybAl1c2VydHJ1c3QDY29tAAAcAAE\": x509: certificate is not valid for any names, but wanted to match dns.twnic.tw" id=13666 question="[{crl.usertrust.com. 28 1}]"
time="2020-07-30T05:52:08+08:00" level=warning msg="query failed, server failed" id=13666 question="[{crl.usertrust.com. 28 1}]"
time="2020-07-30T05:52:14+08:00" level=warning msg="exchangeDNS: remote server failed after 149ms: doHTTP: http request failed: Get \"https://dns.twnic.tw/dns-query?dns=AAABAAABAAAAAAAAA2NybAl1c2VydHJ1c3QDY29tAAAcAAE\": x509: certificate is not valid for any names, but wanted to match dns.twnic.tw" id=61926 question="[{crl.usertrust.com. 28 1}]"
time="2020-07-30T05:52:14+08:00" level=warning msg="query failed, server failed" id=61926 question="[{crl.usertrust.com. 28 1}]"
time="2020-07-30T05:52:18+08:00" level=warning msg="exchangeDNS: remote server failed after 146ms: doHTTP: http request failed: Get \"https://dns.twnic.tw/dns-query?dns=AAABAAABAAAAAAAAA2NybAl1c2VydHJ1c3QDY29tAAAcAAE\": x509: certificate is not valid for any names, but wanted to match dns.twnic.tw" id=20625 question="[{crl.usertrust.com. 28 1}]"
```

**如何重现**

描述一下什么情况下出现了该问题。请尽可能的包含：

- 运行在什么系统

win10 ltsc 2019

- 使用的配置文件

```
# 监听设定
bind:
    addr: "127.0.0.1:53" # [必需]监听地址。IP设为`0.0.0.0`可监听包括IPv6的所有地址。
    protocol: "all" # 监听协议。`tcp`|`udp`|`all`其中之一。留空默认`all`。

# 分流器设定
dispatcher:
    cache: # 缓存设定
        size: 0 # 缓存大小。单位: 条。0表示禁用缓存。如设成512表示最多缓存512条DNS应答。
        min_ttl: 300 # 最小生存时间。单位: 秒。
    max_concurrent_queries: 150 # 最大并发查询数。默认150。

# 上游服务器设定
server:
    # 本地服务器设定
    local:
        addr: "61.139.2.69:53" # 服务器地址。留空表示禁用该服务器。
        protocol: "udp" # 服务器协议。`tcp`|`udp`|`doh`|`dot`其中之一。留空默认`udp`。
        socks5: "" # socks5代理服务器地址。注意：暂不支持udp协议，不支持认证。

        # TCP设定，仅`protocol`为`tcp`时有用。
        tcp:
            idle_timeout: 10 # 空连接超时时间。单位: 秒。0表示禁用连接重用。

        # DoT设定，仅`protocol`为`dot`有用。
        dot:
            server_name: "dns.alidns.com" # [必需] 服务器的域名/证书名。
            idle_timeout: 10 # 空连接超时时间。单位: 秒。0表示禁用连接重用。

        # DoH设定，仅`protocol`为`doh`有用。
        doh:
            url: "https://223.5.5.5/dns-query" # [必需] DoH的URL。

        deny_unusual_types: false # 是否屏蔽不常见(包含多个Question、非A和AAAA)请求。
        deny_results_without_ip: false  # 是否屏蔽没有IP的A和AAAA应答。
        check_cname: false # 域名策略(见下)是否也检查返回应答中的CNAME记录(CNAME深度检查)。

        # IP策略设定
        # 格式: "action:file|action:file|..."
        #
        # IP策略决定本地服务器返回的结果能否被接受。可由多个策略构成，用`|`分割，
        # 处理流程从左至右，如果上一条策略没有命中，将匹配下一条。
        # 如果直到最后都没有命中任何策略，默认接受。
        #
        # `file`为IP表文件的路径。
        # `action`可以是：
        #   `accept`: 如果IP在`file`中，接受。
        #   `deny`: 如果IP在`file`中，拒绝并丢弃。
        #   `deny_all`: 无条件拒绝，用在最后，拒绝直到最后都没有命中任何策略的结果。
        #       相当于把默认处理方式改为`拒绝并丢弃`。后不需要跟`file`。
        #
        # e.g. "deny:./blacklist.txt" 屏蔽`blacklist.txt`里的IP。
        # e.g. "accept:./whitelist.txt|deny_all" 仅允许`whitelist.txt`里的IP。
        # e.g. "deny:./blacklist.txt|accept:./whitelist.txt|deny_all"
        ip_policies: "accept:./chn.list|deny_all"

        # 域名策略设定
        # 格式: "action:file|action:file|..."
        #
        # 域名分流策略根据请求的域名决定本地服务器如何处理该请求。可由多个策略构成，用`|`分割。
        # 处理流程从左至右，如果上一条策略没有命中，将匹配下一条。
        # 如果直到最后都没有命中任何策略，默认为`允许本地服务器处理该请求`。
        #
        # `file`为域名表的路径。
        # `action`可以是
        #   `force`: 如果域名在`file`中，则强制本地服务器处理该请求(不会被远程服务器解析)。
        #       并且最终应答会无视其他所有匹配条件(IP，请求类型等)，强制接受。
        #   `accept`: 如果域名在`file`中，允许本地服务器处理该请求(同时也会送至远程服务器)。
        #   `deny`: 如果域名在`file`中，禁止本地服务器处理该请求(仅由远程服务器解析)。
        #   `deny_all`: 无条件拒绝，用在最后，拒绝直到最后都没有命中任何策略的请求。
        #       相当于把默认处理方式改为`禁止本地服务器处理该请求`。后不需要跟`file`。
        #
        # e.g. "deny:./blacklist.txt" 屏蔽`blacklist.txt`里的域名，这些域名将由远程服务器解析。
        # e.g. "force:./whitelist.txt" 强制本地服务器解析`whitelist.txt`里的域名。
        # e.g. "force:./whitelist.txt|deny_all" 不在其中的域名会一定由远程服务器解析。
        # e.g. "force:./chn_domain.list|accept:./whitelist.txt|deny_all"
        domain_policies: "force:./chn_domain.list"

    # 远程服务器设定
    remote:
        # 以下说明与 local 相同，参见上文。
        addr: "101.101.101.101:443"
        protocol: "doh"
        socks5: ""
        tcp:
            idle_timeout: 10
        dot:
            server_name: "cloudflare-dns.com"
            idle_timeout: 10
        doh:
            url: "https://dns.twnic.tw/dns-query"

        # 延时启动等待时间 单位: 毫秒。
        # 如果是非零值，则不会立即请求remote，而是等待一段时间。
        # 如果本地服务器的返回了结果并且被接受，则不再请求远程服务器。
        # 如果请求本地服务器失败(没有返回结果或结果被拒绝了)，则马上请求远程服务器。
        # 该选项能牺牲一点延时来降低请求远程服务器的次数，进而降低设备负载。
        # `0`表示禁用延时，请求将同步发送
        delay_start: 0

# ECS设定
# 格式: `CIDR`
# 如果填入，来自下游没有ECS的请求将被插入ECS。
# e.g. "1.2.3.0/24"
# e.g. "2001:dd8:1a::/48"
ecs:
    local: "" # 送至local的请求会插入该subnet。
    remote: "" # 送至remote的请求会插入该subnet。
    force_overwrite: false # 强制改写下游请求已包含的ECS。

# CA证书设定
ca:
    path: "" # 证书文件的路径。证书需为PEM格式，可以是ca-bundle。留空默认使用系统自带CA证书。
```

- 使用的启动参数

bat默认的安装和启动

- 做了什么导致问题出现
