### ISSUE TITLE
dig测试中有很多填充的00

### ISSUE THREAD

**Issue by iflamed** [IrineSistiana/mos-chinadns#36]
首先，感谢您热心的反馈问题。

在提交问题之前，请确认1)问题在最新版本中也会出现。2)问题不是由于服务器无法连接(网络问题或服务器设置问题)导致的。

1）master branch
2）macOS Mojave

缺少信息和不符合要求的issus可能会被无视。

---

**出现了什么问题**
dig response pad a lot of 00 00 00

描述一下问题的表现。并附上log或截图。
dig @127.0.0.1 api.github.com

; <<>> DiG 9.10.6 <<>> @127.0.0.1 api.github.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40419
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; PAD: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (".......................................................................................................................................................................................................................................................................................................................................................................................................")
;; QUESTION SECTION:
;api.github.com.            IN  A

;; ANSWER SECTION:
api.github.com.     32  IN  A   192.30.255.117

;; Query time: 245 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Aug 18 18:06:06 CST 2020
;; MSG SIZE  rcvd: 468

**如何重现**

描述一下什么情况下出现了该问题。请尽可能的包含：

- 运行在什么系统
macOS Mojave
- 使用的配置文件
default config.yaml
- 使用的启动参数
./mos-chinadns -c config.yaml -dir2exe
- 做了什么导致问题出现
- nothing

**Comment by IrineSistiana** [comment]
不是bug。

有些加密协议服务器会padding 0。把dns回包大小随机。避免流量分析。

比如Google 的 DoH 指南里就有写。https://developers.google.com/speed/public-dns/docs/doh#privacy_best_practices

**Comment by IrineSistiana** [comment]
确实算个问题。按道理下游协议不加密不应该被pad。

已去。

**Comment by p0we7** [comment]
> 确实算个问题。按道理下游协议不加密不应该被pad。
> 
> 已去。

问题好像依然存在

dig 结果
```
; <<>> DiG 9.10.6 <<>> @127.0.0.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10203
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; PAD: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ("...............................................................................................................................................................................................................................................................................................................................................................................................................")
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		91	IN	A	216.58.200.14

;; Query time: 19 msec
```

config.yaml

```
dispatcher:
    bind: [ "udp://127.0.0.1:53","tcp://127.0.0.1:53","udp://[::1]:53","tcp://[::1]:53" ]

upstream:
    local:
        addr: "127.0.0.1:6053"
        protocol: "udp"
        deduplicate: true
        max_concurrent_queries: 0
        policies:
            deny_unhandlable_types: false

            domain: "accept:./chn_domain.list"

            deny_error_rcode: true

            check_cname: true

            deny_empty_ip_reply: true

            ip: "accept:./chn.list|deny_all"


    remote:
        addr: "1.0.0.1:853"
        protocol: "dot"
        socks5: "127.0.0.1:1080"
        tcp:
            idle_timeout: 10
        dot:
            server_name: "cloudflare-dns.com"
            idle_timeout: 10
        doh:
            url: "https://cloudflare-dns.com/dns-query"

        deduplicate: false
        max_concurrent_queries: 0

        edns0:
            client_subnet: ""
            overwrite_ecs: false

        policies:
            deny_unhandlable_types: false
            domain: "deny:./chn_domain.list" # chn_domain.list里的域名无需remote解析。
            deny_error_rcode: false
            check_cname: false
            deny_empty_ip_reply: false
            ip: ""
```
