### ISSUE TITLE
[BUG]程序不明原因崩溃退出

### ISSUE THREAD

**Issue by p0we7** [IrineSistiana/mos-chinadns#40]
通过 `./mos-chinadns -c config.yaml -debug -dir2exe` 运行程序，过一段时间后出现如下错误并且程序自行结束了。

```
DEBU[0466] dispatch: reply from upstream local accepted, rtt: 1150ms  id=35537 question="[{cdnzz.com. 1 1}]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5fb1d7]

goroutine 896 [running]:
github.com/miekg/dns.(*Msg).CopyTo(0x0, 0xc0004a2900, 0x1f)
	github.com/miekg/dns@v1.1.31/msg.go:1047 +0x37
github.com/miekg/dns.(*Msg).Copy(...)
	github.com/miekg/dns@v1.1.31/msg.go:1043
github.com/IrineSistiana/mos-chinadns/dispatcher.(*upstream).Exchange(0xc0000ac720, 0x877460, 0xc0004df200, 0xc0004e0510, 0x44834f, 0xc0000aca80, 0xc0001a5f20)
	github.com/IrineSistiana/mos-chinadns/dispatcher/upstream.go:121 +0x1e9
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).dispatch.func1(0xc000370460, 0x871400, 0xc0000ac720, 0x877460, 0xc0004df200, 0xc0004e0510, 0xc00032f960, 0xc0000a8a08, 0x5, 0xc0001e4240)
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:107 +0xd2
created by github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).dispatch
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:103 +0x259
```

**如何重现**

未能发现百分百重现方法, 但是运行一段时间后就会随机出现这个问题.
现在还不清楚如何触发崩溃.

系统: Centos 8
启动参数: `./mos-chinadns -c config.yaml -debug -dir2exe` 
场景: mos-chinadns 的国内解析使用的是 smartdns 作为上游
配置文件:
```
dispatcher:
    bind: [ "udp://127.0.0.1:53","tcp://127.0.0.1:53","udp://[::1]:53","tcp://[::1]:53" ]

upstream:
    local:
        addr: "127.0.0.1:6053"
        protocol: "udp"
        deduplicate: true
        max_concurrent_queries: 0
        policies:
            deny_unhandlable_types: false
            domain: "accept:./chn_domain.list"
            deny_error_rcode: true
            check_cname: true
            deny_empty_ip_reply: true
            ip: "accept:./chn.list|deny_all"

    remote:
        addr: "1.0.0.1:853"
        protocol: "dot"
        socks5: "127.0.0.1:1080"
        tcp:
            idle_timeout: 10
        dot:
            server_name: "cloudflare-dns.com"
            idle_timeout: 10
        doh:
            url: "https://cloudflare-dns.com/dns-query"

        deduplicate: false
        max_concurrent_queries: 0

        policies:
            deny_unhandlable_types: false
            domain: "deny:./chn_domain.list" # chn_domain.list里的域名无需remote解析。
            deny_error_rcode: false
            check_cname: false
            deny_empty_ip_reply: false
            ip: ""
```
