### ISSUE TITLE
[BUG]运行一段时间后 cpu 使用大幅增加

### ISSUE THREAD

**Issue by snylonue** [IrineSistiana/mos-chinadns#43]
**出现了什么问题**

mos-chinadns ver: v1.4.2-0-g2d22991
运行一段时间后 cpu 使用率从 < 0.1% 增长到 约 25%，重启后恢复正常
cpu 为 i5-7300HQ

**如何重现**

- 运行在什么系统  `Windows 10.0.18363.1016`
- 使用的配置文件
<details>
  <summary>config.yaml</summary>

```yaml
dispatcher:
    bind: [ "udp://127.0.0.1:5253","tcp://127.0.0.1:5253" ]
upstream:
    local:
        addr: "223.5.5.5:443"
        protocol: "doh" 
        socks5: "" 

        tcp:
            idle_timeout: 10
        dot:
            server_name: "dns.alidns.com" 
            idle_timeout: 10 

        doh:
            url: "https://223.5.5.5/dns-query"

        deduplicate: false
        max_concurrent_queries: 0

        edns0:
            client_subnet: ""
            overwrite_ecs: false

        policies:
            deny_unhandlable_types: false
            domain: "accept:./chn_domain.list"
            deny_error_rcode: true
            check_cname: true
            deny_empty_ip_reply: true
            ip: "accept:./chn.list|deny_all"

    remote:
        addr: "1.0.0.1:853"
        protocol: "dot"
        socks5: ""
        tcp:
            idle_timeout: 10
        dot:
            server_name: "cloudflare-dns.com"
            idle_timeout: 600
        doh:
            url: "https://cloudflare-dns.com/dns-query"

        deduplicate: false
        max_concurrent_queries: 0

        edns0:
            client_subnet: ""
            overwrite_ecs: false

        policies:
            deny_unhandlable_types: false
            domain: "deny:./chn_domain.list" # chn_domain.list里的域名无需remote解析。
            deny_error_rcode: true
            check_cname: false
            deny_empty_ip_reply: false
            ip: ""

ca:
    path: []
```
</details>

- 使用的启动参数 `-c config.yaml`
- 使用场景等相关的信息
从命令行启动，使用一段时间 (20 - 30min)后可能触发问题
如果不发送请求似乎不会触发
<details>
  <summary>问题发生前后的日志</summary>

```
time="2020-08-27T20:19:21+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=4572 question="[{profile.accounts.firefox.com. 1 1}]"
time="2020-08-27T20:19:21+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=23676 question="[{profile.accounts.firefox.com. 1 1}]"
time="2020-08-27T20:19:22+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:17838" id=21750 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:22+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:7586" id=22181 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:23+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=22181 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:23+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=21750 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:25+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=23676 question="[{profile.accounts.firefox.com. 1 1}]"
time="2020-08-27T20:19:25+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=4572 question="[{profile.accounts.firefox.com. 1 1}]"
time="2020-08-27T20:19:27+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=21750 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:27+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=22181 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:28+08:00" level=info msg="printStatus: HeapObjects: 52620 NumGC: 19 PauseTotalNs: 9912100, NumGoroutine: 48"
time="2020-08-27T20:19:29+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:9623" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:29+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:17018" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:29+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:9623" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:29+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:17018" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:30+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:9623" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:30+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:17018" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:32+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:9623" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:32+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:17018" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:34+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:34+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:34+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:34+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:35+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:35+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:36+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:9623" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:36+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:17018" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:37+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:37+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:41+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=63769 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:41+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=23044 question="[{github.com. 1 1}]"
time="2020-08-27T20:19:58+08:00" level=info msg="printStatus: HeapObjects: 54011 NumGC: 19 PauseTotalNs: 9912100, NumGoroutine: 68"
time="2020-08-27T20:20:28+08:00" level=info msg="printStatus: HeapObjects: 54030 NumGC: 19 PauseTotalNs: 9912100, NumGoroutine: 68"
time="2020-08-27T20:20:58+08:00" level=info msg="printStatus: HeapObjects: 9532 NumGC: 20 PauseTotalNs: 9912100, NumGoroutine: 68"
time="2020-08-27T20:21:05+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:3979" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:05+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:51227" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:16+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:16+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:05+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:3979" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:16+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:08+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:3979" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:16+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:06+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:3979" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:16+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:06+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:51227" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:05+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:51227" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:12+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:51227" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:16+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:08+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:51227" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:12+08:00" level=debug msg="listenAndServeUDP 127.0.0.1:5253: new query from 127.0.0.1:3979" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:16+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:16+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:17+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=11405 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:17+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:5253: query failed: context deadline exceeded" id=26453 question="[{github.com. 1 1}]"
time="2020-08-27T20:21:34+08:00" level=info msg="main: received signal: interrupt, program exited"
```
</details>
