### ISSUE TITLE
请教一个多线路配置问题

### ISSUE THREAD

**Issue by douglas-lee** [IrineSistiana/mos-chinadns#56]
场景如下：我需要将chnlist.txt的域名用国内解析，gfwlist.txt用美国线路解析，jplist.txt用日本线路解析，hklist.txt用香港线路解析，按照我的理解，需要添加4个上游，但是在策略配置这一部分，应该怎么配才能实现多线路分流？建议文档里可以补充一下这部分的说明。

**Comment by IrineSistiana** [comment]
```yaml
upstream:
    chn: 
        server: "aliyun"
        policies:
            query: 
                domain: "accept:./chnlist.txt|deny"

    us: 
        server: "google"
        policies:
            query: 
                domain: "accept:./gfwlist.txt|deny"

    jp: 
        server: "some_jp_server"
        policies:
            query: 
                domain: "accept:./jplist.txt|deny"

    ...
```

**Comment by douglas-lee** [comment]
那这样的配置不能用链式？

**Comment by IrineSistiana** [comment]
链式主要是IP分流用的。因为在请求发出去之前你不知道这个域名的地域，希望通过返回的IP判断。然后再去请求一次。

域名分流，你已经直到域名的地域了，没必要用链式。

**Comment by douglas-lee** [comment]
但是所有域名列表里并不能涵盖所有，没有在域名列表里的，依然需要用的IP分流，但是默认我想走usroute，是否可以redirect_us？

**Comment by IrineSistiana** [comment]
```yaml
upstream:

    chn:
        server: "aliyun"
        policies:
            query: 
                domain: "accept:./chnlist.txt"
            reply:
                 ip: "accept:./chn_ip.list|rediecter_hk_server:./hk_ip.list|rediecter_jp_server:./jp_ip.list|....|rediecter_us_server"

    us: 
        server: "google"
        policies:
            query: 
                domain: "accept:./gfwlist.txt|deny"

    jp: 
        server: "some_jp_server"
        policies:
            query: 
                domain: "accept:./jplist.txt|deny"

    ...
```

不知道合不合理，你可以参考wiki琢磨琢磨。
