### ISSUE TITLE
[BUG] config.yaml配置文件中的addr导致doh tcp i/o timeout

### ISSUE THREAD

**Issue by nbsn** [IrineSistiana/mos-chinadns#57]
**出现了什么问题**

config.yaml配置文件中的addr导致doh tcp i/o timeout.

```
Nov 04 23:38:12 dns.nbsn.cn bash[21225]: time="2020-11-04T23:38:12+08:00" level=warning msg="dispatch: [[{dns.pub. 1 1}] 9]: upstream local-dnspod-doh-2 err after 5001ms: doHTTP: http request failed: Get \"https://dns.pub/dns-query?dns=AAABAAABAAAAAAAAA2RucwNwdWIAAAEAAQ\": failed to dial tcp connection: dial tcp 119.29.29.29:443: i/o timeout,"
Nov 04 23:38:12 dns.nbsn.cn bash[21225]: time="2020-11-04T23:38:12+08:00" level=warning msg="dispatch: [[{p1.pstatp.com. 1 1}] 38219]: upstream local-dnspod-doh-2 err after 334ms: doHTTP: http request failed: Get \"https://dns.pub/dns-query?dns=AAABAAABAAAAAAAAAnAxBnBzdGF0cANjb20AAAEAAQ\": failed to dial tcp connection: dial tcp 119.29.29.29:443: i/o timeout,"
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mos-chinadns的版本号：1.5.4

使用的启动参数或启动方式：/root/mos-chinadns/mos-chinadns -c config.yaml -dir2exe

操作系统和平台：CentOS 7

出现问题时候使用的配置文件：

```yaml
server:
    dnspod-doh-1: # <--这个tag可以随意更改，但不能重复。作为该服务器的标识。
        addr: "119.29.29.29:443" # [必需] 服务器地址。
        protocol: "doh" # [必需] 服务器协议。`tcp`|`udp`|`doh`|`dot`其中之一。
        doh:
            url: "https://doh.pub/dns-query" # [必需] DoH的URL。
````

现有默认的行为：用了该配置文件之后，会将doh模式中的url主机url，静态指向addr:中的地址。

这样会有一个问题：

如果服务商的doh中的主机url解析到了不是addr:中指定的地址，会产生大量的doh失效请求，日志反应就是前面的 failed to dial tcp connection: dial tcp 119.29.29.29:443: i/o timeout,"

正面的例子：
以Alidns的举例，因为doh地址正确解析到了223.5.5.5,223.6.6.6的地址，并且用浏览器访问https://223.5.5.5/dns-query，https://223.6.6.6/dns-query，https://dns.alidns.com/dns-query，均能返回正确的结果

```nslookup
> dns.alidns.com
服务器:  UnKnown
Address:  172.16.23.23

非权威应答:
名称:    dns.alidns.com
Addresses:  2400:3200::1
          2400:3200:baba::1
          223.6.6.6
          223.5.5.5

>
```

反面的例子：
以DNSPOD的举例，因为doh地址解析到了162.14.21.178,162.14.21.56的地址，并且用浏览器访问https://119.29.29.29/dns-query，https://119.28.28.28/dns-query不能返回正确的结果

Protocol	Address	
DNS, IPv4	119.29.29.29 and 119.28.28.28
DNS-over-HTTPS	https://doh.pub/dns-query
DNS-over-HTTPS	https://dns.pub/dns-query
DNS-over-TLS	tls://dns.pub

```nslookup
C:\Users\Sunny>nslookup
默认服务器:  UnKnown
Address:  172.16.23.23

> doh.pub
服务器:  UnKnown
Address:  172.16.23.23

非权威应答:
名称:    doh.pub
Addresses:  162.14.21.178
          162.14.21.56
>

```

所以需要手动将config.yaml字段中改为以下才能正常工作

```yaml
server:
    dnspod-doh-1: # <--这个tag可以随意更改，但不能重复。作为该服务器的标识。
        addr: "162.14.21.178:443" # [必需] 服务器地址。
        protocol: "doh" # [必需] 服务器协议。`tcp`|`udp`|`doh`|`dot`其中之一。
        doh:
            url: "https://doh.pub/dns-query" # [必需] DoH的URL。
````

如果遇到提供商修改地址，需要debug才能查看到具体的结果。

建议：
将配置文件中server字段中参数：addr升级为Bootstrap DNS服务器地址，用Bootstrap DNS服务器用于解析您指定为上游的 DoH / DoT 解析器的 IP 地址。
