### ISSUE TITLE
[Feature request]有无可能为ipset.rule添加upstream或server配匹

### ISSUE THREAD

**Issue by ffftwo** [IrineSistiana/mos-chinadns#58]
感谢您热心的提出建议。在提交建议前，请知晓mos-chinadns主要功能是分流，原则只添加和分流有关的功能。

---

**Feature request**

要添加什么功能？

```yaml
upstream:
    chn:
        server: "aliyun"
        policies:
            query:
                domain: "accept:./chn_domain.list|deny"
    remote:
        server: "googledns"
        policies:
            query:
                domain: "deny:./chn_domain.list|accept"

ipset:
    rule:
        - set_name4: "set1"
          #通过googledns查询并reply的ip都加入set1
          server: "accept:googledns|deny"
```

**为什么**

通过ipset实现简单的白名单机制

**Comment by IrineSistiana** [comment]
ipset 的 `domain` 也可以白名单。和`chn.domain: "accept:./chn_domain.list|deny"`一样不就是白名单了么。

**Comment by ffftwo** [comment]
> ipset 的 `domain` 也可以白名单。和`chn.domain: "accept:./chn_domain.list|deny"`一样不就是白名单了么。

明白了,之前没想到,现在按你说的实现了白名单

```yaml
upstream:
    chn:
        server: "aliyun"
        policies:
            query:
                domain: "accept:./chn_domain.list|deny"
    remote:
        server: "googledns"
        policies:
            query:
                domain: "deny:./chn_domain.list|accept"

ipset:
    rule:
        - set_name4: "chniplist"
          #通过aliyun查询并reply的ip都加入chnlist
          domain: "accept:./chn_domain.list|deny"
```

```shell
#将chniplist之外的流量转到代理
iptables -t nat -A PREROUTING -i br-lan -p tcp -m set ! --match-set chniplist dst -j REDIRECT --to-port xxx
```

---
再说一点其它的,希望可以考虑一下哈  

我最开始的想法是把chn_domain.list之外的域名ip放到set1中,然后用iptables转到代理,这样理论上和上面的方法没有区别,只不过不需要额外处理内网ip等一些例外,相对方便和"便携"一点点.  

其实不需要像我标题说的匹配upstream或server,我发现在`ipset.rule.domain`中使用`deny:xxx|accept`,最后的这个accept并不会把除了xxx之外的域名ip放入ipset,如果能像`upstream`中一样,做为兜底策略生效就好了  

```yaml
ipset:
    rule:
        - set_name4: "set1"
          #最后的accept把未匹配的域名ip放入set1
          domain: "deny:./chn_domain.list|accept"
```

```shell
#将set1的流量转到代理
iptables -t nat -A PREROUTING -i br-lan -p tcp -m set --match-set set1 dst -j REDIRECT --to-port
```
