### ISSUE TITLE
安装为 windows 服务后无法解析国外地址

### ISSUE THREAD

**Issue by Miroxyz** [IrineSistiana/mos-chinadns#59]
**出现了什么问题**

描述一下问题的表现。可以直接附上截图或log。如果log看不出报错，请用`-debug`参数启动程序获取更详细的调试log。

安装为 windows 服务后无法解析国外地址，使用命令行的形式启动是正常的。
不知道和我的上网方式是否有关？公司内使用 socks5 + Proxifier 代理上网的

**使用命令行**
![image](https://user-images.githubusercontent.com/69784329/99020891-6be08680-259a-11eb-8534-c659dc2b168b.png)

**使用 windows 服务**
![image](https://user-images.githubusercontent.com/69784329/99020541-ccbb8f00-2599-11eb-88f6-6fa69b40b8c1.png)

```txt
time="2020-11-13T10:05:31+08:00" level=info msg="main: mos-chinadns ver: v1.5.6-1-g6fabe74"
time="2020-11-13T10:05:31+08:00" level=info msg="main: arch: amd64 os: windows"
time="2020-11-13T10:05:31+08:00" level=info msg="loadFromCacheOrRawDisk: open file ./chn_domain.list"
time="2020-11-13T10:05:31+08:00" level=info msg="loadFromCacheOrRawDisk: open file ./non_chn_domain.list"
time="2020-11-13T10:05:31+08:00" level=info msg="loadFromCacheOrRawDisk: open file ./chn_ip.list"
time="2020-11-13T10:05:31+08:00" level=info msg="StartServer: udp server started at 127.0.0.1:53"
time="2020-11-13T10:05:31+08:00" level=info msg="StartServer: tcp server started at 127.0.0.1:53"
time="2020-11-13T10:05:31+08:00" level=info msg="StartServer: udp server started at [::1]:53"
time="2020-11-13T10:05:31+08:00" level=info msg="StartServer: tcp server started at [::1]:53"
time="2020-11-13T10:05:53+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 40363]: upstream remote err after 2029ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:05:53+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 40363]: query failed: all upstreams failed or not respond in time"
time="2020-11-13T10:05:58+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 40363]: upstream remote err after 2034ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:05:58+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 40363]: query failed: all upstreams failed or not respond in time"
time="2020-11-13T10:06:03+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 40363]: upstream remote err after 2033ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:06:03+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 40363]: query failed: all upstreams failed or not respond in time"
time="2020-11-13T10:06:28+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 44917]: upstream remote err after 2034ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:06:28+08:00" level=warning msg="listenAndServeTCP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 44917]: query failed: all upstreams failed or not respond in time"
time="2020-11-13T10:06:36+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 8091]: upstream remote err after 2048ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:06:36+08:00" level=warning msg="listenAndServeTCP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 8091]: query failed: all upstreams failed or not respond in time"
time="2020-11-13T10:09:12+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 50888]: upstream remote err after 2035ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:09:12+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 50888]: query failed: all upstreams failed or not respond in time"
time="2020-11-13T10:09:17+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 50888]: upstream remote err after 2044ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:09:17+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 50888]: query failed: all upstreams failed or not respond in time"
time="2020-11-13T10:09:21+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 49508]: upstream remote err after 2040ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:09:21+08:00" level=warning msg="listenAndServeTCP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 49508]: query failed: all upstreams failed or not respond in time"
time="2020-11-13T10:09:29+08:00" level=warning msg="dispatch: [[{www.youtube.com. 1 1}] 30284]: upstream remote err after 2036ms: failed to dial tcp connection: dial tcp 8.8.8.8:53: connectex: No connection could be made because the target machine actively refused it.,"
time="2020-11-13T10:09:29+08:00" level=warning msg="listenAndServeTCP 127.0.0.1:53: [[{www.youtube.com. 1 1}] 30284]: query failed: all upstreams failed or not respond in time"

```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mos-chinadns的版本号：v1.5.6

使用的启动参数或启动方式：windows 服务

操作系统和平台：win10 2004

进行了什么操作导致了问题的出现：安装为 windows 服务后

使用的配置文件：

```yaml
dispatcher:
    bind: [ "udp4://127.0.0.1:53","tcp4://127.0.0.1:53","udp6://[::1]:53","tcp6://[::1]:53" ]
    max_udp_size: 1280
upstream:
    local:
        server: "aliyun"
        policies:
            query:
                unhandlable_types: "accept"
                domain: "accept:./chn_domain.list|deny:./non_chn_domain.list"
            reply:
                error_rcode: "deny"
                cname: "accept:./chn_domain.list"
                without_ip: "deny"
                ip: "accept:./chn_ip.list|deny"
    remote:
        server: "google"
        policies:
            query:
                unhandlable_types: "accept"
                domain: "deny:./chn_domain.list|accept"
            reply:
                error_rcode: ""
                cname: ""
                without_ip: ""
                ip: ""
server:
    aliyun:
        addr: "192.168.100.2:53"
        protocol: "udp"
        socks5: ""
        tcp:
            idle_timeout: 5
        dot:
            server_name: "dns.alidns.com"
            idle_timeout: 5
        doh:
            url: "https://223.5.5.5/dns-query"
        deduplicate: false
        edns0:
            client_subnet:
                ipv4: ""
                ipv6: ""
            overwrite_ecs: false
    google:
        addr: "8.8.8.8:53"
        protocol: "tcp"
        socks5: ""
        tcp:
            idle_timeout: 5
        dot:
            server_name: "dns.google"
            idle_timeout: 5
        doh:
            url: "https://dns.google/dns-query"
        deduplicate: false
        edns0:
            client_subnet:
                ipv4: ""
                ipv6: ""
            overwrite_ecs: false
ipset:
    check_cname: false
    mask4: 0
    mask6: 0
    rule:
        - set_name4: ""
          set_name6: ""
          domain: ""
        - set_name4: ""
          set_name6: ""
          domain: ""
ca:
    path: []

````

**Comment by IrineSistiana** [comment]
不是mos-chinadns的问题。

更像是什么防火墙把`tcp://8.8.8.8:53`给禁了。

**Comment by Miroxyz** [comment]
> 不是mos-chinadns的问题。
> 
> 更像是什么防火墙把`tcp://8.8.8.8:53`给禁了。

但是用相同的配置，用命令行是可以正常解析的。不知道和我的上网方式是否有关？公司内使用 socks5 + Proxifier 代理上网的

**Comment by IrineSistiana** [comment]
> 但是用相同的配置，用命令行是可以正常解析的。不知道和我的上网方式是否有关？公司内使用 socks5 + Proxifier 代理上网的

这我就不知道辽。用命令行启动还是用Windows服务启动程序本身的运行方式是没有区别的。除了用户名，Windows服务是以`SYSTEM`身份启动的。

大概率 Proxifier  的锅。

**Comment by Miroxyz** [comment]
> 这我就不知道辽。用命令行启动还是用Windows服务启动程序本身的运行方式是没有区别的。除了用户名，Windows服务是以`SYSTEM`身份启动的。
> 
> 大概率 Proxifier 的锅。

好的，我自己再排查看看，感谢。

**Comment by delphinuz** [comment]
```
google:
  addr: "8.8.8.8:53"
  protocol: "tcp"
  socks5: "127.0.0.1:1080"
```
这里的1080 port是v2ray提供的socks5，但出现以下讯息。确定1080 port是可以正常使用的。


```

time="2021-03-06T22:08:39+08:00" level=warning msg="dispatch: [[{google.com. 28 1}] 5]: upstream remote err after 2586ms: EOF,"
time="2021-03-06T22:08:39+08:00" level=warning msg="listenAndServeUDP 127.0.0.1:53: [[{google.com. 28 1}] 5]: query failed: all upstreams failed or not respond in time"
```
